# Generated by Django 3.0.3 on 2020-03-03 16:24

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='in_queue', max_length=10)),
                ('video', models.FileField(upload_to=core.models.get_video_path, validators=[core.models.validate_video])),
                ('subtitle', models.FileField(upload_to=core.models.get_subtitle_path, validators=[core.models.validate_subtitle])),
            ],
        ),
    ]
