# Generated by Django 3.0.4 on 2020-03-14 13:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200314_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochunk',
            name='audio_chunk',
            field=models.FileField(upload_to=core.models.get_audio_chunk_path, validators=[core.models.validate_audio]),
        ),
    ]
