# Generated by Django 3.0.4 on 2020-03-14 15:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200314_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochunk',
            name='audio_chunk',
            field=models.FileField(storage=core.models.OverwriteStorage(), upload_to=core.models.get_audio_chunk_path, validators=[core.models.validate_audio]),
        ),
    ]
